### PR TITLE
Simpler compiler urls

### PR DESCRIPTION
**Pull request by KevinDyer**

### CODE REVIEW

**Comment by KevinDyer** [comment]
One of the driving factors of this change is the ability to specify an compiler baseUrl in an environment variable (ie `BASE_URL_L114="https://us-central1-graffiticode.cloudfunctions.net/L114"`). There is a unit test for this but I also manually tested that this works using the graffiticode cloud function.

**Comment by KevinDyer** [comment]
This should probably still be a WIP PR because I should write tests for the lang router

**Comment by KevinDyer** [comment]
Added tests for the lang router. This is ready for review

**Comment by jeffdyer** [comment]
Made one tweak to setting the default protocol for local compiles.

**Pull request merged**
